<?php

/** @var \Kontor\API\Domain\ApiToken[] $tokens */
/** @var \Kontor\API\Domain\WebhookSubscription[] $subscriptions */
/** @var \Kontor\API\Domain\WebhookDelivery[] $deliveries */
/** @var array<string, \Kontor\API\Contracts\ApiResourceInterface> $resources */
/** @var array<string, mixed> $openApi */
/** @var array{kind: string, label: string, value: string}|null $oneTimeSecret */
/** @var bool $canManageWebhooks */
/** @var string $adminUrl */
/** @var string $csrfName */
/** @var string $csrfValue */
/** @var callable $e */
?>
<div class="ProcessKontor pw-module-workspace kontor-shell">
  <header class="pw-module-head kontor-pagehead"><div><p class="kontor-eyebrow">External ecosystem · REST v1</p><h2>API</h2><p>Issue scoped credentials, inspect registered resources, and operate webhook subscriptions.</p></div><div class="pw-module-actions kontor-pagehead__actions"><a class="uk-button uk-button-secondary kontor-button kontor-button--ghost" href="/api/kontor/v1/organizations">REST endpoint</a></div></header>
  <?php if ($oneTimeSecret !== null): ?><section class="uk-alert uk-alert-warning kontor-warning"><strong><?= $e(ucfirst($oneTimeSecret['kind'])) ?> secret for <?= $e($oneTimeSecret['label']) ?></strong><p>Copy this value now. It will not be shown again.</p><code data-testid="one-time-secret"><?= $e($oneTimeSecret['value']) ?></code></section><?php endif; ?>
  <section class="uk-card uk-card-default uk-card-small uk-card-body kontor-card pw-table-panel uk-overflow-auto kontor-tablewrap"><header class="kontor-sectionhead"><div><p class="kontor-eyebrow">Authentication</p><h3>API tokens</h3></div></header><form class="uk-form-stacked kontor-nativeform" method="post" action="<?= $e($adminUrl) ?>api-token/"><input type="hidden" name="<?= $e($csrfName) ?>" value="<?= $e($csrfValue) ?>"><label class="kontor-nativefield"><span>Name *</span><input name="name" required></label><label class="kontor-nativefield kontor-nativefield--wide"><span>Scopes</span><input name="scopes" placeholder="organizations:read, organizations:write"></label><label class="kontor-nativefield"><span>Expires</span><input name="expires_at" type="datetime-local"></label><div class="kontor-nativeform__actions"><button class="uk-button uk-button-primary kontor-button" type="submit">Issue token</button></div></form><?php if ($tokens !== []): ?><table class="uk-table uk-table-divider uk-table-hover uk-table-middle uk-table-small kontor-table"><thead><tr><th>Name</th><th>Scopes</th><th>Status</th><th>Last used</th><th></th></tr></thead><tbody><?php foreach ($tokens as $token): ?><tr><td><strong><?= $e($token->name) ?></strong></td><td><?= $e($token->scopes === [] ? 'unrestricted' : implode(', ', $token->scopes)) ?></td><td><span class="uk-label kontor-pill<?= $token->isActive() ? '' : ' kontor-pill--inactive' ?>"><?= $e($token->status) ?></span></td><td><?= $e($token->lastUsedAt?->format('Y-m-d H:i') ?? 'never') ?></td><td><?php if ($token->isActive()): ?><form method="post" action="<?= $e($adminUrl) ?>api-token-revoke/"><input type="hidden" name="<?= $e($csrfName) ?>" value="<?= $e($csrfValue) ?>"><input type="hidden" name="token_uid" value="<?= $e($token->uid->toString()) ?>"><button class="uk-button uk-button-secondary kontor-button kontor-button--ghost" type="submit">Revoke</button></form><?php endif; ?></td></tr><?php endforeach; ?></tbody></table><?php else: ?><div class="pw-empty-state uk-placeholder uk-text-center kontor-empty"><p>No API tokens issued.</p></div><?php endif; ?></section>
  <section class="uk-card uk-card-default uk-card-small uk-card-body kontor-card pw-table-panel uk-overflow-auto kontor-tablewrap"><header class="kontor-sectionhead"><div><p class="kontor-eyebrow">OpenAPI 3.0</p><h3>Registered resources</h3></div></header><?php if ($resources !== []): ?><table class="uk-table uk-table-divider uk-table-hover uk-table-middle uk-table-small kontor-table"><thead><tr><th>Resource</th><th>Fields</th><th>Operations</th></tr></thead><tbody><?php foreach ($resources as $resource): ?><?php $schema = $resource->schema(); ?><tr><td><strong><code>/<?= $e($resource->key()) ?></code></strong></td><td><?= $e(implode(', ', array_keys($schema->fields))) ?></td><td>list, find<?= $schema->supportsCreate ? ', create' : '' ?><?= $schema->supportsUpdate ? ', update' : '' ?><?= $schema->supportsDelete ? ', delete' : '' ?></td></tr><?php endforeach; ?></tbody></table><?php endif; ?><details><summary>OpenAPI document</summary><pre><code><?= $e(json_encode($openApi, JSON_PRETTY_PRINT | JSON_UNESCAPED_SLASHES)) ?></code></pre></details></section>
  <?php if ($canManageWebhooks): ?><section class="uk-card uk-card-default uk-card-small uk-card-body kontor-card pw-table-panel uk-overflow-auto kontor-tablewrap"><header class="kontor-sectionhead"><div><p class="kontor-eyebrow">Signed event delivery</p><h3>Webhooks</h3></div></header><form class="uk-form-stacked kontor-nativeform" method="post" action="<?= $e($adminUrl) ?>api-webhook/"><input type="hidden" name="<?= $e($csrfName) ?>" value="<?= $e($csrfValue) ?>"><label class="kontor-nativefield kontor-nativefield--wide"><span>Endpoint URL *</span><input name="url" type="url" placeholder="https://example.test/hooks/kontor" required></label><label class="kontor-nativefield"><span>Event name *</span><input name="event_pattern" placeholder="invoice.issued" required></label><div class="kontor-nativeform__actions"><button class="uk-button uk-button-primary kontor-button" type="submit">Add webhook</button></div></form><?php if ($subscriptions !== []): ?><table class="uk-table uk-table-divider uk-table-hover uk-table-middle uk-table-small kontor-table"><thead><tr><th>Event</th><th>Endpoint</th><th>Status</th><th>Failures</th><th></th></tr></thead><tbody><?php foreach ($subscriptions as $subscription): ?><tr><td><strong><?= $e($subscription->eventPattern) ?></strong></td><td><code><?= $e($subscription->url) ?></code></td><td><?= $e($subscription->status) ?></td><td><?= $e((string) $subscription->consecutiveFailures) ?></td><td><form method="post" action="<?= $e($adminUrl) ?>api-webhook-archive/"><input type="hidden" name="<?= $e($csrfName) ?>" value="<?= $e($csrfValue) ?>"><input type="hidden" name="subscription_uid" value="<?= $e($subscription->uid->toString()) ?>"><button class="uk-button uk-button-secondary kontor-button kontor-button--ghost" type="submit">Archive</button></form></td></tr><?php endforeach; ?></tbody></table><?php else: ?><div class="pw-empty-state uk-placeholder uk-text-center kontor-empty"><p>No webhook subscriptions.</p></div><?php endif; ?></section><?php endif; ?>
  <section class="uk-card uk-card-default uk-card-small uk-card-body kontor-card pw-table-panel uk-overflow-auto kontor-tablewrap"><header class="kontor-sectionhead"><div><p class="kontor-eyebrow">Observability</p><h3>Recent webhook deliveries</h3></div></header><?php if ($deliveries !== []): ?><table class="uk-table uk-table-divider uk-table-hover uk-table-middle uk-table-small kontor-table"><thead><tr><th>When</th><th>Event</th><th>Status</th><th>Attempts</th><th>Response</th></tr></thead><tbody><?php foreach ($deliveries as $delivery): ?><tr><td><?= $e($delivery->createdAt->format('Y-m-d H:i:s')) ?></td><td><?= $e($delivery->eventName) ?></td><td><?= $e($delivery->status) ?></td><td><?= $e((string) $delivery->attemptCount) ?></td><td><?= $e($delivery->responseCode !== null ? (string) $delivery->responseCode : ($delivery->lastError ?? '—')) ?></td></tr><?php endforeach; ?></tbody></table><?php else: ?><div class="pw-empty-state uk-placeholder uk-text-center kontor-empty"><p>No webhook deliveries yet.</p></div><?php endif; ?></section>
</div>
