<?php

/** @var \Kontor\Automation\Domain\AutomationRule|null $rule */
/** @var array{name: string, triggerEvent: string} $values */
/** @var string $error */
/** @var \Kontor\Automation\Domain\RuleCondition[] $conditions */
/** @var \Kontor\Automation\Domain\RuleAction[] $actions */
/** @var \Kontor\Automation\Domain\ExecutionLog[] $logs */
/** @var string[] $actionHandlers */
/** @var bool $canManage */
/** @var bool $canDryRun */
/** @var string $adminUrl */
/** @var string $csrfName */
/** @var string $csrfValue */
/** @var callable $e */
?>
<div class="kontor-shell">
  <header class="kontor-formhead"><a class="kontor-formhead__back" href="<?= $e($adminUrl) ?>automations/"><i class="fa fa-arrow-left"></i> Back to automations</a><p class="kontor-eyebrow">Automation · Rule builder</p><h2><?= $e($rule?->name ?? 'Create rule') ?></h2></header>
  <?php if ($error !== ''): ?><div class="kontor-warning"><strong><?= $e($error) ?></strong></div><?php endif; ?>
  <?php if ($rule === null): ?>
    <form class="kontor-card kontor-nativeform" method="post" action="./"><input type="hidden" name="<?= $e($csrfName) ?>" value="<?= $e($csrfValue) ?>"><label class="kontor-nativefield kontor-nativefield--wide"><span>Name *</span><input name="name" value="<?= $e($values['name']) ?>" required></label><label class="kontor-nativefield kontor-nativefield--wide"><span>Trigger event *</span><input name="trigger_event" value="<?= $e($values['triggerEvent']) ?>" required></label><div class="kontor-nativeform__actions"><button class="kontor-button" type="submit" name="submit_save" value="1">Create rule</button></div></form>
  <?php else: ?>
    <section class="kontor-card"><div class="kontor-detailgrid"><div><span>Trigger</span><strong><?= $e($rule->triggerEvent) ?></strong></div><div><span>Status</span><strong><?= $e($rule->status) ?></strong></div><div><span>Conditions</span><strong><?= $e((string) count($conditions)) ?></strong></div><div><span>Actions</span><strong><?= $e((string) count($actions)) ?></strong></div></div></section>
    <section class="kontor-card kontor-tablewrap"><header class="kontor-sectionhead"><div><p class="kontor-eyebrow">IF · AND semantics</p><h3>Conditions</h3></div></header><?php if ($canManage): ?><form class="kontor-nativeform" method="post" action="<?= $e($adminUrl) ?>automation-condition/"><input type="hidden" name="<?= $e($csrfName) ?>" value="<?= $e($csrfValue) ?>"><input type="hidden" name="rule_uid" value="<?= $e($rule->uid->toString()) ?>"><label class="kontor-nativefield"><span>Payload field *</span><input name="field" placeholder="request.priority" required></label><label class="kontor-nativefield"><span>Operator *</span><select name="operator"><?php foreach (\Kontor\Automation\Domain\RuleCondition::OPERATORS as $operator): ?><option value="<?= $e($operator) ?>"><?= $e(str_replace('_', ' ', $operator)) ?></option><?php endforeach; ?></select></label><label class="kontor-nativefield"><span>Expected value</span><input name="value"></label><div class="kontor-nativeform__actions"><button class="kontor-button kontor-button--ghost" type="submit">Add condition</button></div></form><?php endif; ?><?php if ($conditions !== []): ?><table class="kontor-table"><thead><tr><th>Field</th><th>Operator</th><th>Value</th></tr></thead><tbody><?php foreach ($conditions as $condition): ?><tr><td><strong><?= $e($condition->field) ?></strong></td><td><?= $e(str_replace('_', ' ', $condition->operator)) ?></td><td><?= $e($condition->value ?? 'null') ?></td></tr><?php endforeach; ?></tbody></table><?php else: ?><div class="kontor-empty"><p>No conditions: every matching event will pass.</p></div><?php endif; ?></section>
    <section class="kontor-card kontor-tablewrap"><header class="kontor-sectionhead"><div><p class="kontor-eyebrow">THEN · Registry</p><h3>Actions</h3></div></header><?php if ($canManage): ?><form class="kontor-nativeform" method="post" action="<?= $e($adminUrl) ?>automation-action/"><input type="hidden" name="<?= $e($csrfName) ?>" value="<?= $e($csrfValue) ?>"><input type="hidden" name="rule_uid" value="<?= $e($rule->uid->toString()) ?>"><label class="kontor-nativefield"><span>Handler *</span><select name="action_key"><?php foreach ($actionHandlers as $handler): ?><option value="<?= $e($handler) ?>"><?= $e($handler) ?></option><?php endforeach; ?></select></label><label class="kontor-nativefield kontor-nativefield--wide"><span>Parameters JSON</span><textarea name="params_json" rows="5">{}</textarea><small><code>tasks.create</code> example: <code>{"title":"Follow up {{ customer.name }}","priority":"high","dueInMinutes":60,"linkToTrigger":true}</code></small></label><div class="kontor-nativeform__actions"><button class="kontor-button kontor-button--ghost" type="submit">Add action</button></div></form><?php endif; ?><?php if ($actions !== []): ?><table class="kontor-table"><thead><tr><th>Handler</th><th>Parameters</th></tr></thead><tbody><?php foreach ($actions as $action): ?><tr><td><strong><?= $e($action->actionKey) ?></strong></td><td><code><?= $e(json_encode($action->params, JSON_UNESCAPED_SLASHES)) ?></code></td></tr><?php endforeach; ?></tbody></table><?php else: ?><div class="kontor-empty"><p>Add a registered action handler.</p></div><?php endif; ?></section>
    <?php if ($canDryRun): ?><section class="kontor-card"><header class="kontor-sectionhead"><div><p class="kontor-eyebrow">Test bench</p><h3>Run event payload</h3></div></header><form class="kontor-nativeform" method="post" action="<?= $e($adminUrl) ?>automation-run/"><input type="hidden" name="<?= $e($csrfName) ?>" value="<?= $e($csrfValue) ?>"><input type="hidden" name="rule_uid" value="<?= $e($rule->uid->toString()) ?>"><label class="kontor-nativefield kontor-nativefield--wide"><span>Payload JSON *</span><textarea name="payload_json" rows="7" required>{"request":{"priority":"high"},"message":"QA automation"}</textarea></label><label class="kontor-nativefield"><span><input name="dry_run" type="checkbox" value="1" checked> Dry run</span></label><div class="kontor-nativeform__actions"><button class="kontor-button" type="submit">Run payload</button></div></form></section><?php endif; ?>
    <section class="kontor-card kontor-tablewrap"><header class="kontor-sectionhead"><div><p class="kontor-eyebrow">Append-only</p><h3>Execution log</h3></div></header><?php if ($logs !== []): ?><table class="kontor-table"><thead><tr><th>When</th><th>Mode</th><th>Matched</th><th>Actions</th><th>Error</th></tr></thead><tbody><?php foreach ($logs as $log): ?><tr><td><?= $e($log->occurredAt->format('Y-m-d H:i:s')) ?></td><td><?= $log->dryRun ? 'dry run' : 'live' ?></td><td><span class="kontor-pill<?= $log->matched ? '' : ' kontor-pill--inactive' ?>"><?= $log->matched ? 'yes' : 'no' ?></span></td><td><?= $e((string) count($log->actionsResult)) ?></td><td><?= $e($log->error ?? '—') ?></td></tr><?php endforeach; ?></tbody></table><?php else: ?><div class="kontor-empty"><p>No evaluations yet.</p></div><?php endif; ?></section>
  <?php endif; ?>
</div>
