<?php

/** @var \Kontor\Automation\Domain\AutomationRule[] $rules */
/** @var \Kontor\Automation\Domain\ExecutionLog[] $logs */
/** @var bool $canManage */
/** @var string $adminUrl */
/** @var callable $e */
?>
<div class="ProcessKontor pw-module-workspace kontor-shell">
  <header class="pw-module-head kontor-pagehead"><div><p class="kontor-eyebrow">Extensibility · Event pipeline</p><h2>Automations</h2><p>Evaluate real Kontor events through conditions and registered actions.</p></div><?php if ($canManage): ?><div class="pw-module-actions kontor-pagehead__actions"><a class="uk-button uk-button-primary kontor-button" href="<?= $e($adminUrl) ?>automation/"><i class="fa fa-plus"></i> New rule</a></div><?php endif; ?></header>
  <section class="uk-card uk-card-default uk-card-small uk-card-body kontor-card pw-table-panel uk-overflow-auto kontor-tablewrap"><?php if ($rules !== []): ?><table class="uk-table uk-table-divider uk-table-hover uk-table-middle uk-table-small kontor-table"><thead><tr><th>Rule</th><th>Trigger event</th><th>Status</th><th>Updated</th></tr></thead><tbody><?php foreach ($rules as $rule): ?><tr><td><strong><a href="<?= $e($adminUrl) ?>automation/?id=<?= $e(rawurlencode($rule->uid->toString())) ?>"><?= $e($rule->name) ?></a></strong></td><td><?= $e($rule->triggerEvent) ?></td><td><span class="uk-label kontor-pill"><?= $e($rule->status) ?></span></td><td><?= $e($rule->updatedAt->format('Y-m-d H:i')) ?></td></tr><?php endforeach; ?></tbody></table><?php else: ?><div class="pw-empty-state uk-placeholder uk-text-center kontor-empty"><i class="fa fa-bolt"></i><h3>No automation rules</h3><p>Create a trigger → conditions → actions pipeline.</p></div><?php endif; ?></section>
  <section class="uk-card uk-card-default uk-card-small uk-card-body kontor-card pw-table-panel uk-overflow-auto kontor-tablewrap"><header class="kontor-sectionhead"><div><p class="kontor-eyebrow">Observability</p><h3>Recent executions</h3></div></header><?php if ($logs !== []): ?><table class="uk-table uk-table-divider uk-table-hover uk-table-middle uk-table-small kontor-table"><thead><tr><th>When</th><th>Event</th><th>Mode</th><th>Matched</th><th>Result</th></tr></thead><tbody><?php foreach ($logs as $log): ?><tr><td><?= $e($log->occurredAt->format('Y-m-d H:i:s')) ?></td><td><?= $e($log->triggerEvent) ?></td><td><?= $log->dryRun ? 'dry run' : 'live' ?></td><td><?= $log->matched ? 'yes' : 'no' ?></td><td><?= $e($log->recursionBlocked ? 'recursion blocked' : ($log->error ?? (string) count($log->actionsResult) . ' action(s)')) ?></td></tr><?php endforeach; ?></tbody></table><?php else: ?><div class="pw-empty-state uk-placeholder uk-text-center kontor-empty"><p>No executions recorded yet.</p></div><?php endif; ?></section>
</div>
