<?php

/** @var \Kontor\Mail\Domain\Mailbox[] $mailboxes */
/** @var \Kontor\Mail\Domain\MailMessage[] $messages */
/** @var \Kontor\Mail\Domain\MailMessage|null $selected */
/** @var array<int, array<string, mixed>> $relations */
/** @var array<string, \Kontor\Mail\Contracts\InboundMailAdapterInterface> $adapters */
/** @var bool $canManageMailboxes */
/** @var bool $canSend */
/** @var string $adminUrl */
/** @var string $csrfName */
/** @var string $csrfValue */
/** @var callable $e */
?>
<div class="ProcessKontor pw-module-workspace kontor-shell">
  <header class="pw-module-head kontor-pagehead"><div><p class="kontor-eyebrow">Advanced capabilities · Communications</p><h2>Mail</h2><p>Shared mailboxes, outbound history, inbound adapters, and links to business entities.</p></div></header>
  <section class="uk-card uk-card-default uk-card-small uk-card-body kontor-card pw-table-panel uk-overflow-auto kontor-tablewrap"><header class="kontor-sectionhead"><div><p class="kontor-eyebrow">Team identities</p><h3>Shared mailboxes</h3></div></header><?php if ($canManageMailboxes): ?><form class="uk-form-stacked kontor-nativeform" method="post" action="<?= $e($adminUrl) ?>mail-mailbox/"><input type="hidden" name="<?= $e($csrfName) ?>" value="<?= $e($csrfValue) ?>"><label class="kontor-nativefield"><span>Name *</span><input name="name" required></label><label class="kontor-nativefield"><span>Email address *</span><input name="email_address" type="email" required></label><div class="kontor-nativeform__actions"><button class="uk-button uk-button-primary kontor-button" type="submit">Create mailbox</button></div></form><?php endif; ?><?php if ($mailboxes !== []): ?><table class="uk-table uk-table-divider uk-table-hover uk-table-middle uk-table-small kontor-table"><thead><tr><th>Name</th><th>Address</th><th>Status</th></tr></thead><tbody><?php foreach ($mailboxes as $mailbox): ?><tr><td><strong><?= $e($mailbox->name) ?></strong></td><td><?= $e($mailbox->emailAddress) ?></td><td><?= $e($mailbox->status) ?></td></tr><?php endforeach; ?></tbody></table><?php else: ?><div class="pw-empty-state uk-placeholder uk-text-center kontor-empty"><p>No shared mailboxes.</p></div><?php endif; ?></section>
  <?php if ($canSend): ?><section class="uk-card uk-card-default uk-card-small uk-card-body kontor-card"><header class="kontor-sectionhead"><div><p class="kontor-eyebrow">Transport and history</p><h3>Compose outbound</h3></div></header><form class="uk-form-stacked kontor-nativeform" method="post" action="<?= $e($adminUrl) ?>mail-outbound/"><input type="hidden" name="<?= $e($csrfName) ?>" value="<?= $e($csrfValue) ?>"><label class="kontor-nativefield"><span>Mailbox</span><select name="mailbox_uid"><option value="">None</option><?php foreach ($mailboxes as $mailbox): ?><option value="<?= $e($mailbox->uid->toString()) ?>"><?= $e($mailbox->name) ?></option><?php endforeach; ?></select></label><label class="kontor-nativefield"><span>From *</span><input name="from_address" type="email" required></label><label class="kontor-nativefield kontor-nativefield--wide"><span>To *</span><input name="to_addresses" placeholder="one@example.test, two@example.test" required></label><label class="kontor-nativefield kontor-nativefield--wide"><span>CC</span><input name="cc_addresses"></label><label class="kontor-nativefield kontor-nativefield--wide"><span>Subject *</span><input name="subject" required></label><label class="kontor-nativefield kontor-nativefield--wide"><span>Body *</span><textarea name="body_text" rows="6" required></textarea></label><label class="kontor-nativefield"><span><input type="checkbox" name="dry_run" value="1" checked> Simulate transport (records history, sends nothing)</span></label><div class="kontor-nativeform__actions"><button class="uk-button uk-button-primary kontor-button" type="submit">Process outbound</button></div></form></section><?php endif; ?>
  <?php if ($canManageMailboxes): ?><section class="uk-card uk-card-default uk-card-small uk-card-body kontor-card"><header class="kontor-sectionhead"><div><p class="kontor-eyebrow">Inbound adapter</p><h3>Receive raw email</h3></div></header><form class="uk-form-stacked kontor-nativeform" method="post" action="<?= $e($adminUrl) ?>mail-inbound/"><input type="hidden" name="<?= $e($csrfName) ?>" value="<?= $e($csrfValue) ?>"><label class="kontor-nativefield"><span>Mailbox</span><select name="mailbox_uid"><option value="">Unassigned mailbox</option><?php foreach ($mailboxes as $mailbox): ?><option value="<?= $e($mailbox->uid->toString()) ?>"><?= $e($mailbox->name) ?></option><?php endforeach; ?></select></label><label class="kontor-nativefield"><span>Adapter *</span><select name="adapter"><?php foreach ($adapters as $key => $adapter): ?><option value="<?= $e($key) ?>"><?= $e($key) ?></option><?php endforeach; ?></select></label><label class="kontor-nativefield kontor-nativefield--wide"><span>Raw email *</span><textarea name="raw_email" rows="8" placeholder="From: sender@example.test&#10;To: support@example.test&#10;Subject: Hello&#10;&#10;Message body" required></textarea></label><div class="kontor-nativeform__actions"><button class="uk-button uk-button-primary kontor-button" type="submit">Receive message</button></div></form></section><?php endif; ?>
  <section class="uk-card uk-card-default uk-card-small uk-card-body kontor-card pw-table-panel uk-overflow-auto kontor-tablewrap"><header class="kontor-sectionhead"><div><p class="kontor-eyebrow">Persistent history</p><h3>Messages</h3></div></header><?php if ($messages !== []): ?><table class="uk-table uk-table-divider uk-table-hover uk-table-middle uk-table-small kontor-table"><thead><tr><th>When</th><th>Direction</th><th>Subject</th><th>From / To</th><th>Status</th></tr></thead><tbody><?php foreach ($messages as $message): ?><tr><td><?= $e($message->occurredAt->format('Y-m-d H:i')) ?></td><td><?= $e($message->direction) ?></td><td><strong><a href="<?= $e($adminUrl) ?>mail/?id=<?= $e(rawurlencode($message->uid->toString())) ?>"><?= $e($message->subject) ?></a></strong></td><td><?= $e($message->isOutbound() ? implode(', ', $message->toAddresses) : $message->fromAddress) ?></td><td><?= $e($message->status) ?></td></tr><?php endforeach; ?></tbody></table><?php else: ?><div class="pw-empty-state uk-placeholder uk-text-center kontor-empty"><p>No mail history.</p></div><?php endif; ?></section>
  <?php if ($selected !== null): ?><section class="uk-card uk-card-default uk-card-small uk-card-body kontor-card"><header class="kontor-sectionhead"><div><p class="kontor-eyebrow"><?= $e($selected->direction) ?> · <?= $e($selected->status) ?></p><h3><?= $e($selected->subject) ?></h3></div></header><div class="kontor-detailgrid"><div><span>From</span><strong><?= $e($selected->fromAddress) ?></strong></div><div><span>To</span><strong><?= $e(implode(', ', $selected->toAddresses)) ?></strong></div><div><span>CC</span><strong><?= $e($selected->ccAddresses !== [] ? implode(', ', $selected->ccAddresses) : '—') ?></strong></div><div><span>Assigned</span><strong><?= $e($selected->assignedTo !== null ? (string) $selected->assignedTo : 'unassigned') ?></strong></div></div><pre><code><?= $e($selected->bodyText) ?></code></pre><header class="kontor-sectionhead"><div><p class="kontor-eyebrow">Business graph</p><h3>Entity links</h3></div></header><form class="uk-form-stacked kontor-nativeform" method="post" action="<?= $e($adminUrl) ?>mail-link/"><input type="hidden" name="<?= $e($csrfName) ?>" value="<?= $e($csrfValue) ?>"><input type="hidden" name="message_uid" value="<?= $e($selected->uid->toString()) ?>"><label class="kontor-nativefield"><span>Entity type *</span><input name="entity_type" placeholder="contact" required></label><label class="kontor-nativefield"><span>Entity UID *</span><input name="entity_uid" required></label><div class="kontor-nativeform__actions"><button class="uk-button uk-button-secondary kontor-button kontor-button--ghost" type="submit">Link entity</button></div></form><?php if ($relations !== []): ?><table class="uk-table uk-table-divider uk-table-hover uk-table-middle uk-table-small kontor-table"><thead><tr><th>Entity type</th><th>Entity UID</th><th>Relation</th></tr></thead><tbody><?php foreach ($relations as $relation): ?><tr><td><?= $e((string) $relation['targetType']) ?></td><td><code><?= $e((string) $relation['targetUid']) ?></code></td><td><?= $e((string) $relation['relationType']) ?></td></tr><?php endforeach; ?></tbody></table><?php else: ?><div class="pw-empty-state uk-placeholder uk-text-center kontor-empty"><p>No entity links.</p></div><?php endif; ?></section><?php endif; ?>
</div>
