<?php

/** @var \Kontor\Marketplace\Domain\Registry[] $registries */
/** @var \Kontor\Marketplace\Domain\MarketplaceListing[] $listings */
/** @var \Kontor\Marketplace\Domain\Publisher[] $publishers */
/** @var \Kontor\Marketplace\Domain\Advisory[] $advisories */
/** @var array<string, \Kontor\Marketplace\DTO\InstallabilityResult> $installability */
/** @var array{listings: int, advisories: int, skipped: string[]}|null $syncResult */
/** @var bool $canManage */
/** @var string $adminUrl */
/** @var string $csrfName */
/** @var string $csrfValue */
/** @var callable $e */
?>
<div class="kontor-shell">
  <header class="kontor-pagehead"><div><p class="kontor-eyebrow">External ecosystem · Discovery</p><h2>Marketplace</h2><p>Manage registry sources, inspect component metadata, and surface publisher trust and advisories.</p></div></header>
  <?php if ($syncResult !== null): ?><section class="kontor-warning"><strong>Registry synchronized</strong><p><?= $e((string) $syncResult['listings']) ?> listing(s), <?= $e((string) $syncResult['advisories']) ?> advisory item(s), <?= $e((string) count($syncResult['skipped'])) ?> skipped.</p><?php if ($syncResult['skipped'] !== []): ?><ul><?php foreach ($syncResult['skipped'] as $skipped): ?><li><?= $e($skipped) ?></li><?php endforeach; ?></ul><?php endif; ?></section><?php endif; ?>
  <section class="kontor-card kontor-tablewrap"><header class="kontor-sectionhead"><div><p class="kontor-eyebrow">Official and custom sources</p><h3>Registries</h3></div></header><?php if ($canManage): ?><form class="kontor-nativeform" method="post" action="<?= $e($adminUrl) ?>marketplace-registry/"><input type="hidden" name="<?= $e($csrfName) ?>" value="<?= $e($csrfValue) ?>"><label class="kontor-nativefield"><span>Name *</span><input name="name" placeholder="partner" required></label><label class="kontor-nativefield kontor-nativefield--wide"><span>Index URL *</span><input name="url" type="url" required></label><label class="kontor-nativefield"><span><input name="trusted" type="checkbox" value="1"> Trusted publisher source</span></label><div class="kontor-nativeform__actions"><button class="kontor-button" type="submit">Add registry</button></div></form><?php endif; ?><table class="kontor-table"><thead><tr><th>Name</th><th>Type</th><th>Trusted</th><th>Status</th><th>Last sync</th><th></th></tr></thead><tbody><?php foreach ($registries as $registry): ?><tr><td><strong><?= $e($registry->name) ?></strong><br><small><?= $e($registry->url) ?></small></td><td><?= $e($registry->type) ?></td><td><?= $registry->trusted ? 'yes' : 'no' ?></td><td><?= $e($registry->status) ?></td><td><?= $e($registry->lastSyncedAt?->format('Y-m-d H:i') ?? 'never') ?></td><td><?php if ($canManage): ?><form method="post" action="<?= $e($adminUrl) ?>marketplace-registry-toggle/"><input type="hidden" name="<?= $e($csrfName) ?>" value="<?= $e($csrfValue) ?>"><input type="hidden" name="registry_name" value="<?= $e($registry->name) ?>"><button class="kontor-button kontor-button--ghost" type="submit"><?= $registry->isActive() ? 'Disable' : 'Enable' ?></button></form><?php endif; ?></td></tr><?php endforeach; ?></tbody></table></section>
  <?php if ($canManage): ?><section class="kontor-card"><header class="kontor-sectionhead"><div><p class="kontor-eyebrow">Deterministic import · max 1 MB</p><h3>Synchronize registry JSON</h3></div></header><form class="kontor-nativeform" method="post" action="<?= $e($adminUrl) ?>marketplace-import/"><input type="hidden" name="<?= $e($csrfName) ?>" value="<?= $e($csrfValue) ?>"><label class="kontor-nativefield"><span>Registry *</span><select name="registry_name"><?php foreach ($registries as $registry): ?><option value="<?= $e($registry->name) ?>"><?= $e($registry->name) ?></option><?php endforeach; ?></select></label><label class="kontor-nativefield kontor-nativefield--wide"><span>Payload JSON *</span><textarea name="payload_json" rows="10" placeholder='{"components":[],"advisories":[]}' required></textarea></label><div class="kontor-nativeform__actions"><button class="kontor-button" type="submit">Synchronize payload</button></div></form></section><?php endif; ?>
  <section class="kontor-card kontor-tablewrap"><header class="kontor-sectionhead"><div><p class="kontor-eyebrow">Metadata and recommendation</p><h3>Listings</h3></div></header><?php if ($listings !== []): ?><table class="kontor-table"><thead><tr><th>Component</th><th>Version</th><th>Registry</th><th>Publisher</th><th>Recommendation</th></tr></thead><tbody><?php foreach ($listings as $listing): ?><?php $check = $installability[$listing->registryName . ':' . $listing->package]; ?><tr><td><strong><?= $e($listing->title ?? $listing->name) ?></strong><br><code><?= $e($listing->package) ?></code></td><td><?= $e($listing->version) ?></td><td><?= $e($listing->registryName) ?></td><td><?= $e($listing->publisherName ?? '—') ?></td><td><span class="kontor-pill<?= $check->isInstallable() ? '' : ' kontor-pill--inactive' ?>"><?= $check->isInstallable() ? 'installable' : 'blocked' ?></span><?php if (!$check->dependencies->satisfied): ?><br><small><?= $e(implode('; ', $check->dependencies->problems())) ?></small><?php endif; ?><?php if ($check->hasCriticalAdvisory()): ?><br><small>Critical advisory affects this version.</small><?php endif; ?></td></tr><?php endforeach; ?></tbody></table><?php else: ?><div class="kontor-empty"><p>No component listings synchronized.</p></div><?php endif; ?></section>
  <section class="kontor-card kontor-tablewrap"><header class="kontor-sectionhead"><div><p class="kontor-eyebrow">Identity</p><h3>Publishers</h3></div></header><?php if ($publishers !== []): ?><table class="kontor-table"><thead><tr><th>Name</th><th>URL</th><th>Verified</th></tr></thead><tbody><?php foreach ($publishers as $publisher): ?><tr><td><strong><?= $e($publisher->name) ?></strong></td><td><?= $e($publisher->url ?? '—') ?></td><td><?= $publisher->verified ? 'yes' : 'no' ?></td></tr><?php endforeach; ?></tbody></table><?php else: ?><div class="kontor-empty"><p>No publishers known.</p></div><?php endif; ?></section>
  <section class="kontor-card kontor-tablewrap"><header class="kontor-sectionhead"><div><p class="kontor-eyebrow">Security</p><h3>Advisories</h3></div></header><?php if ($advisories !== []): ?><table class="kontor-table"><thead><tr><th>Severity</th><th>Package</th><th>Affected</th><th>Title</th><th>Published</th></tr></thead><tbody><?php foreach ($advisories as $advisory): ?><tr><td><span class="kontor-pill<?= $advisory->severity === 'critical' ? ' kontor-pill--inactive' : '' ?>"><?= $e($advisory->severity) ?></span></td><td><code><?= $e($advisory->package) ?></code></td><td><?= $e($advisory->affectedVersions) ?></td><td><strong><?= $e($advisory->title) ?></strong></td><td><?= $e($advisory->publishedAt->format('Y-m-d')) ?></td></tr><?php endforeach; ?></tbody></table><?php else: ?><div class="kontor-empty"><p>No advisories synchronized.</p></div><?php endif; ?></section>
</div>
