<?php

declare(strict_types=1);

namespace Kontor\SDK\Scaffolding;

/**
 * `make:component` (kontor.md Substage 7.4). Generates the FULL canonical
 * directory tree from kontor.md section 7 — every hand-built package in
 * this monorepo so far only used the leaner subset it actually needed,
 * but a scaffolder's job is to faithfully reproduce the spec, not the
 * shortcuts taken under it. Empty directories are represented by a
 * `.gitkeep` file, since git tracks files, not directories.
 */
final class ComponentScaffolder
{
    /**
     * @var string[]
     */
    private const SRC_SUBDIRECTORIES = [
        'Admin', 'Application', 'Domain', 'Infrastructure', 'Contracts',
        'DTO', 'Events', 'Listeners', 'Services', 'Repositories',
        'Validation', 'Policies', 'Providers', 'Support',
    ];

    /**
     * @var string[]
     */
    private const RESOURCE_SUBDIRECTORIES = [
        'views', 'assets', 'translations/en', 'translations/fr',
        'translations/de', 'translations/es', 'templates', 'demo',
    ];

    /**
     * @var string[]
     */
    private const TEST_SUBDIRECTORIES = ['Unit', 'Integration', 'Migration', 'E2E'];

    public function __construct(
        private readonly string $name,
        private readonly string $packageSlug,
        private readonly string $title,
        private readonly string $description,
        private readonly string $category = 'business',
        private readonly string $authorName = 'Maxim Semenov',
        private readonly string $authorUrl = 'https://github.com/mxmsmnv',
    ) {
    }

    /**
     * @return array<string, string> relative path => file contents
     */
    public function generate(string $targetDir, bool $dryRun = false): array
    {
        $files = $this->files();

        if (!$dryRun) {
            foreach ($files as $relativePath => $contents) {
                $fullPath = rtrim($targetDir, '/').'/'.$relativePath;
                @mkdir(dirname($fullPath), 0777, recursive: true);
                file_put_contents($fullPath, $contents);
            }
        }

        return $files;
    }

    /**
     * @return array<string, string>
     */
    private function files(): array
    {
        $files = [
            "Kontor{$this->name}.module.php" => $this->moduleFile(),
            'kontor.json' => $this->kontorJsonFile(),
            'composer.json' => $this->composerJsonFile(),
            'LICENSE' => $this->licenseFile(),
            'README.md' => $this->readmeFile(),
            'CHANGELOG.md' => $this->changelogFile(),
        ];

        foreach (self::SRC_SUBDIRECTORIES as $subdirectory) {
            $files["src/{$subdirectory}/.gitkeep"] = '';
        }

        $files['migrations/.gitkeep'] = '';

        foreach (self::RESOURCE_SUBDIRECTORIES as $subdirectory) {
            $files["resources/{$subdirectory}/.gitkeep"] = '';
        }

        foreach (self::TEST_SUBDIRECTORIES as $subdirectory) {
            $files["tests/{$subdirectory}/.gitkeep"] = '';
        }

        $files['docs/.gitkeep'] = '';

        return $files;
    }

    private function moduleFile(): string
    {
        $name = $this->name;
        $slug = $this->packageSlug;

        return <<<PHP
        <?php

        namespace ProcessWire;

        use Kontor\\Core\\Infrastructure\\Migrations\\MigrationRunner;
        use Kontor\\Core\\Infrastructure\\Registry\\ComponentRegistry;
        use Kontor\\Core\\Infrastructure\\Registry\\TranslationRegistry;

        /**
         * Kontor{$name} bootstrap module. Generated by ComponentScaffolder
         * (kontor.md Substage 7.4) — add this component's migrations,
         * repositories and services as it grows.
         */
        class Kontor{$name} extends WireData implements Module
        {
            public static function getModuleInfo(): array
            {
                return [
                    'title' => '{$this->title}',
                    'summary' => '{$this->description}',
                    'version' => '100',
                    'author' => '{$this->authorName}',
                    'href' => '{$this->authorUrl}',
                    'icon' => 'cube',
                    'singular' => true,
                    'autoload' => true,
                    'requires' => ['Kontor'],
                    'permissions' => [],
                ];
            }

            public function init(): void
            {
                /** @var Kontor \$kontor */
                \$kontor = \$this->wire()->modules->get('Kontor');

                \$this->registerTranslations(\$kontor->container()->get(TranslationRegistry::class));
            }

            private function registerTranslations(TranslationRegistry \$translations): void
            {
                foreach (['en', 'fr', 'de', 'es'] as \$language) {
                    \$path = __DIR__ . "/resources/translations/{\$language}/messages.json";

                    if (!is_file(\$path)) {
                        continue;
                    }

                    \$strings = json_decode((string) file_get_contents(\$path), associative: true, flags: JSON_THROW_ON_ERROR);
                    \$translations->register('Kontor{$name}', \$language, \$strings);
                }
            }

            private function pdo(): \\PDO
            {
                return \\Kontor\\Core\\Infrastructure\\Database\\TranslatingPDO::wrap(\$this->wire()->database);
            }

            public function ___install(): void
            {
                \$pdo = \$this->pdo();

                \$runner = new MigrationRunner(\$pdo);
                \$runner->ensureLedgerExists();
                \$runner->run([
                    // Add this component's migrations here.
                ]);

                \$components = new ComponentRegistry(\$pdo);
                \$components->markInstalled('{$slug}', self::getModuleInfo()['version'], '{$slug}');
                \$components->enable('{$slug}');
            }

            /**
             * Codex rule #10: ordinary uninstall must not remove user data.
             */
            public function ___uninstall(): void
            {
                \$this->message(\$this->_('Kontor{$name} module removed. Data was kept intact.'));
            }
        }

        PHP;
    }

    private function kontorJsonFile(): string
    {
        $data = [
            '$schema' => 'https://kontor.dev/schema/component.v1.json',
            'schemaVersion' => 1,
            'name' => "Kontor{$this->name}",
            'title' => $this->title,
            'description' => $this->description,
            'version' => '1.0.0',
            'type' => 'business',
            'category' => $this->category,
            'license' => 'MIT',
            'author' => ['name' => $this->authorName, 'url' => $this->authorUrl],
            'repository' => "https://github.com/mxmsmnv/Kontor{$this->name}",
            'package' => "kontor/{$this->packageSlug}",
            'namespace' => "Kontor\\{$this->name}",
            'processWireModule' => "Kontor{$this->name}",
            'requires' => [
                'php' => '>=8.2',
                'processwire' => '>=3.0.240',
                'kontor/sdk' => '^1.0',
                'kontor/core' => '^1.0',
            ],
            'suggests' => new \stdClass(),
            'conflicts' => new \stdClass(),
            'capabilities' => [],
            'permissions' => [],
            'admin' => ['sections' => [], 'routes' => []],
            'services' => [],
            'events' => ['publishes' => [], 'subscribes' => []],
            'providers' => [
                'backup' => null, 'import' => [], 'export' => [],
                'search' => [], 'reports' => [], 'health' => [],
            ],
            'translations' => ['source' => 'en', 'languages' => ['en', 'fr', 'de', 'es']],
            'migrations' => ['path' => 'migrations', 'supportsRollback' => true],
            'storage' => ['tables' => [], 'directories' => []],
            'cli' => [],
            'security' => ['externalConnections' => [], 'sensitiveData' => []],
        ];

        return json_encode($data, JSON_PRETTY_PRINT | JSON_UNESCAPED_SLASHES).PHP_EOL;
    }

    private function composerJsonFile(): string
    {
        $data = [
            'name' => "kontor/{$this->packageSlug}",
            'description' => $this->description,
            'type' => 'library',
            'license' => 'MIT',
            'version' => '1.0.0',
            'authors' => [['name' => $this->authorName, 'homepage' => $this->authorUrl]],
            'require' => [
                'php' => '>=8.2',
                'kontor/sdk' => '^1.0',
                'kontor/core' => '^1.0',
            ],
            'require-dev' => ['phpunit/phpunit' => '^11.0'],
            'repositories' => [
                ['type' => 'path', 'url' => '../sdk'],
                ['type' => 'path', 'url' => '../..'],
            ],
            'autoload' => [
                'psr-4' => [
                    "Kontor\\{$this->name}\\" => 'src/',
                    "Kontor\\{$this->name}\\Migrations\\" => 'migrations/',
                ],
            ],
            'autoload-dev' => [
                'psr-4' => ["Kontor\\{$this->name}\\Tests\\" => 'tests/'],
            ],
            'minimum-stability' => 'stable',
        ];

        return json_encode($data, JSON_PRETTY_PRINT | JSON_UNESCAPED_SLASHES).PHP_EOL;
    }

    private function licenseFile(): string
    {
        $year = date('Y');

        return <<<TEXT
        MIT License

        Copyright (c) {$year} {$this->authorName}

        Permission is hereby granted, free of charge, to any person obtaining a copy
        of this software and associated documentation files (the "Software"), to deal
        in the Software without restriction, including without limitation the rights
        to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
        copies of the Software, and to permit persons to whom the Software is
        furnished to do so, subject to the following conditions:

        The above copyright notice and this permission notice shall be included in all
        copies or substantial portions of the Software.

        THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
        IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
        FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
        AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
        LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
        OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
        SOFTWARE.

        TEXT;
    }

    private function readmeFile(): string
    {
        return <<<MD
        # {$this->title}

        `kontor/{$this->packageSlug}` — {$this->description}

        Generated by `Kontor\\SDK\\Scaffolding\\ComponentScaffolder`
        (kontor.md Substage 7.4). Replace this file with a real description
        once the component has actual contents.

        ## Testing

        ```bash
        composer install
        vendor/bin/phpunit
        ```

        MD;
    }

    private function changelogFile(): string
    {
        return <<<MD
        # Changelog

        All notable changes to `kontor/{$this->packageSlug}` are documented here.
        The format follows [Keep a Changelog](https://keepachangelog.com/).

        ## [Unreleased]

        ### Added

        - Scaffolded package skeleton.

        MD;
    }
}
